<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable-upload [
    <!ELEMENT timetable-upload (timetables)>
    <!ATTLIST timetable-upload operation (insert|update) "update">
    <!ELEMENT timetables (timetable+)>
    <!ELEMENT timetable (id?, datetime, activity_id, location_id, trainer_id)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT datetime (#PCDATA)>
    <!ELEMENT activity_id (#PCDATA)>
    <!ELEMENT location_id (#PCDATA)>
    <!ELEMENT trainer_id (#PCDATA)>
]>
<!-- Example of Insert -->
<timetable-upload operation="insert">
    <timetables>
        <timetable>
            <datetime>2024-06-04 11:30:00</datetime>
            <activity_id>12</activity_id>
            <location_id>1</location_id>
            <trainer_id>5</trainer_id>
        </timetable>
        <timetable>
            <datetime>2024-06-05 6:00:00</datetime>
            <activity_id>9</activity_id>
            <location_id>2</location_id>
            <trainer_id>4</trainer_id>
        </timetable>
        <timetable>
            <datetime>2024-06-06 10:00:00</datetime>
            <activity_id>11</activity_id>
            <location_id>1</location_id>
            <trainer_id>5</trainer_id>
        </timetable>
        <timetable>
            <datetime>2024-06-07 9:30:00</datetime>
            <activity_id>7</activity_id>
            <location_id>2</location_id>
            <trainer_id>4</trainer_id>
        </timetable>
    </timetables>
</timetable-upload>

<!-- Example of Update  -->
<!-- <timetable-upload operation="update">
    <timetables>
        <timetable>
            <id>23</id>
            <datetime>2024-05-06 10:00:00</datetime>
            <activity_id>11</activity_id>
            <location_id>1</location_id>
            <trainer_id>5</trainer_id>
        </timetable>
    </timetables>
</timetable-upload> -->